In [4]:
# tpm of this super phi
from temporal_emergence import CoarseGrainer, PhiCalculator, Helpers
import pyphi
import numpy as np
import matplotlib.pyplot as plt
import jupyter
import seaborn as sns
jupyter.textOutputLimit = 0

TPM_max_phi = np.loadtxt("results/macro_micros_fixed/micro_206_292_occs_200_bin_0.0135875_skip_4.csv")

element_coarse_grainings = [[[0], [1,2,3]], [[0,1,2],[3]], [[0], [1,2], [3]], [[0], [1], [2], [3]]]
states, num_states_l = CoarseGrainer.get_state_maps(element_coarse_grainings)

TPM_max_phi_coarse_grained = CoarseGrainer.coarse_grain_nonbinary_TPM(TPM_max_phi,states[4], num_states_l[4])

network = pyphi.Network(
TPM_max_phi_coarse_grained,
num_states_per_node=num_states_l[4]
)

states = Helpers.get_nary_states(2,2)

phis = []
stored_sia_00 = None
for state in states:
    subsystem = pyphi.Subsystem(network, state)
    sia = pyphi.compute.sia(subsystem)
    phis.append(sia.phi)
    if state == (0,0):
        stored_sia_00 = sia
        unpartitioned_ces = sia.ces
        print(sia.ces)
        print(sia.partitioned_ces)
        print(sia.cut)

print(phis)
print(sum(phis) / len(phis))

[[0.64333333 0.00333333 0.35       0.00333333]
 [0.575      0.         0.41       0.015     ]
 [0.40555556 0.00111111 0.58722222 0.00611111]
 [0.51       0.00333333 0.47666667 0.01      ]]
Network([[0.64333333 0.00333333 0.35       0.00333333]
 [0.575      0.         0.41       0.015     ]
 [0.40555556 0.00111111 0.58722222 0.00611111]
 [0.51       0.00333333 0.47666667 0.01      ]], cm=[[1. 1.]
 [1. 1.]])


Computing concepts:   0% 0/3 [00:00<?, ?it/s]

Computing concepts:  33% 1/3 [00:00<00:00,  4.99it/s]

Evaluating Φ cuts:   0% 0/2 [00:00<?, ?it/s]

Evaluating Φ cuts:  50% 1/2 [00:00<00:00,  3.82it/s]

════════════════════════════════════════════════════════════
            Cause-effect structure (3 concepts)             
════════════════════════════════════════════════════════════
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  
           Concept: Mechanism = [A], φ = 0.002637           
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  
              MIC                         MIE               
  ┌──────────────────────────┐┌──────────────────────────┐  
  │  φ = 0.002637            ││  φ = 0.015124            │  
  │  Purview = [A]           ││  Purview = [A, B]        │  
  │  MIP:                    ││  MIP:                    │  
  │     A     ∅              ││     A     ∅              │  
  │    ─── ✕ ───             ││    ─── ✕ ───             │  
  │     ∅     A              ││     ∅    A,B             │  
  │  Repertoire:             ││  Repertoire:             │  
  │    ┌────────────────┐    ││    ┌───────────────────┐ │  
  │    │ S    Pr(S)     

Computing concepts:   0% 0/3 [00:00<?, ?it/s]

Computing concepts:  33% 1/3 [00:00<00:00,  6.14it/s]

Evaluating Φ cuts:   0% 0/2 [00:00<?, ?it/s]

Evaluating Φ cuts:  50% 1/2 [00:00<00:00,  3.78it/s]

Computing concepts:   0% 0/3 [00:00<?, ?it/s]

Computing concepts:  33% 1/3 [00:00<00:00,  6.74it/s]

Evaluating Φ cuts:   0% 0/2 [00:00<?, ?it/s]

Evaluating Φ cuts:  50% 1/2 [00:00<00:00,  3.46it/s]

Computing concepts:   0% 0/3 [00:00<?, ?it/s]

Computing concepts:  33% 1/3 [00:00<00:00,  7.13it/s]

Evaluating Φ cuts:   0% 0/2 [00:00<?, ?it/s]

Evaluating Φ cuts:  50% 1/2 [00:00<00:00,  3.52it/s]

[0.0, 0.0, -0.026519999999999988, 0.00015100000000001224]
-0.006592249999999994


In [ ]:
### all_16_macro_micros_connected[a][1][5]
"""
inp = np.stack(all_16_macro_micros_connected[:,1])
print(np.unravel_index(np.nanargmin(inp), inp.shape))
print(inp.shape)
print(all_16_macro_micros_connected[600,2])
print(np.nanmin(inp))
print(np.sum(inp < 0))
print(np.sum(inp < 1))
print(np.sum(inp < 0) / np.sum(inp < 1) * 100)
"""